---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "entOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: true
  tasks:

  - name: Install EPEL Repo (prereq)
    dnf: 
      name: epel-release
      state: latest
    when: ansible_distribution == "CentOS"
  
  - name: install Nagios (CentOS)
    dnf:
      name: nagios
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install Nagios (Ubuntu)
    apt:
      name: nagios3
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Start Nagios (CentOS)
    service:
      name: nagios
      state: restarted
      enabled: true
    when: ansible_distribution == "CentOS"

  - name: Start Nagios (Ubuntu)
    service:
      name: nagios3
      state: restarted
      enabled: true
    when: ansible_distribution == "Ubuntu"

  - name: Install Nagios Dependencies (CentOS)
    dnf:
      name:
        - gd-devel
        - libpng-devel
        - freetype-devel
        - gcc
        - glibc
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Install Nagios Dependencies (Ubuntu)
    apt:
      name:
        - libgd-dev
        - libpng-dev
        - libfreetype6-dev
        - gcc
        - libc6-dev
      state: latest
    when: ansible_distribution == "Ubuntu"
